import { RawData } from "./types";

export const rawData: RawData = {
  totalRounds: 30,
  teams: {
    MrGenericUser: "CT",
    Nana4321: "CT",
    Spacebro: "CT",
    Wild_West: "T",
    atomic: "T",
    awesomaave: "T",
    honestpretzels: "T",
    jiaedin: "T",
    kevin: "CT",
    nosidE: "CT",
  },
  kills: {
    MrGenericUser: 11,
    Nana4321: 16,
    Spacebro: 14,
    Wild_West: 15,
    atomic: 34,
    awesomaave: 9,
    honestpretzels: 22,
    jiaedin: 21,
    kevin: 48,
    nosidE: 31,
  },
  assists: {
    MrGenericUser: 7,
    Nana4321: 6,
    Spacebro: 5,
    Wild_West: 4,
    atomic: 3,
    awesomaave: 8,
    honestpretzels: 6,
    jiaedin: 7,
    kevin: 3,
    nosidE: 1,
  },
  deaths: {
    MrGenericUser: 22,
    Nana4321: 23,
    Spacebro: 22,
    Wild_West: 23,
    atomic: 21,
    awesomaave: 24,
    honestpretzels: 26,
    jiaedin: 27,
    kevin: 18,
    nosidE: 17,
  },
  timesTraded: {
    MrGenericUser: 6,
    Nana4321: 5,
    Spacebro: 3,
    Wild_West: 5,
    atomic: 2,
    awesomaave: 3,
    honestpretzels: 5,
    jiaedin: 5,
    kevin: 2,
    nosidE: 5,
  },
  headshotPct: {
    MrGenericUser: 36,
    Nana4321: 38,
    Spacebro: 57,
    Wild_West: 20,
    atomic: 35,
    awesomaave: 33,
    honestpretzels: 27,
    jiaedin: 52,
    kevin: 42,
    nosidE: 52,
  },
  kd: {
    MrGenericUser: 0.5,
    Nana4321: 0.7,
    Spacebro: 0.64,
    Wild_West: 0.65,
    atomic: 1.62,
    awesomaave: 0.38,
    honestpretzels: 0.85,
    jiaedin: 0.78,
    kevin: 2.67,
    nosidE: 1.82,
  },
  kdiff: {
    MrGenericUser: -11,
    Nana4321: -7,
    Spacebro: -8,
    Wild_West: -8,
    atomic: 13,
    awesomaave: -15,
    honestpretzels: -4,
    jiaedin: -6,
    kevin: 30,
    nosidE: 14,
  },
  kpr: {
    MrGenericUser: 0.37,
    Nana4321: 0.53,
    Spacebro: 0.47,
    Wild_West: 0.5,
    atomic: 1.13,
    awesomaave: 0.3,
    honestpretzels: 0.73,
    jiaedin: 0.7,
    kevin: 1.6,
    nosidE: 1.03,
  },
  adr: {
    MrGenericUser: 50,
    Nana4321: 68,
    Spacebro: 56,
    Wild_West: 47,
    atomic: 115,
    awesomaave: 51,
    honestpretzels: 78,
    jiaedin: 87,
    kevin: 148,
    nosidE: 100,
  },
  kast: {
    MrGenericUser: 70,
    Nana4321: 77,
    Spacebro: 57,
    Wild_West: 60,
    atomic: 67,
    awesomaave: 53,
    honestpretzels: 67,
    jiaedin: 70,
    kevin: 87,
    nosidE: 77,
  },
  impact: {
    MrGenericUser: 0.48,
    Nana4321: 0.8,
    Spacebro: 0.66,
    Wild_West: 0.71,
    atomic: 2.04,
    awesomaave: 0.34,
    honestpretzels: 1.23,
    jiaedin: 1.18,
    kevin: 3.04,
    nosidE: 1.8,
  },
  hltv: {
    MrGenericUser: 0.69,
    Nana4321: 0.91,
    Spacebro: 0.69,
    Wild_West: 0.69,
    atomic: 1.53,
    awesomaave: 0.47,
    honestpretzels: 0.99,
    jiaedin: 1,
    kevin: 2.24,
    nosidE: 1.54,
  },
  utilDamage: {
    MrGenericUser: 60,
    Spacebro: 111,
    Wild_West: 8,
    atomic: 155,
    honestpretzels: 81,
    jiaedin: 83,
    kevin: 100,
    nosidE: 81,
  },
  flashAssists: {
    Wild_West: 1,
    atomic: 3,
    honestpretzels: 1,
    nosidE: 2,
  },
  enemiesFlashed: {
    Nana4321: 5,
    Wild_West: 3,
    atomic: 15,
    honestpretzels: 16,
    jiaedin: 3,
    kevin: 10,
    nosidE: 16,
  },
  teammatesFlashed: {
    Nana4321: 2,
    Wild_West: 5,
    atomic: 6,
    honestpretzels: 3,
    jiaedin: 2,
    kevin: 5,
    nosidE: 13,
  },
  rounds: [
    {
      winner: "CT",
      winReason: 7,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 7,
    },
    {
      winner: "CT",
      winReason: 7,
    },
    {
      winner: "CT",
      winReason: 7,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "T",
      winReason: 9,
    },
    {
      winner: "T",
      winReason: 9,
    },
    {
      winner: "T",
      winReason: 9,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "T",
      winReason: 1,
    },
    {
      winner: "T",
      winReason: 9,
    },
    {
      winner: "CT",
      winReason: 12,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 7,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 7,
    },
    {
      winner: "T",
      winReason: 1,
    },
    {
      winner: "T",
      winReason: 1,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "T",
      winReason: 1,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "CT",
      winReason: 8,
    },
    {
      winner: "T",
      winReason: 9,
    },
    {
      winner: "CT",
      winReason: 8,
    },
  ],
  headToHead: {
    MrGenericUser: {
      Wild_West: 4,
      atomic: 3,
      awesomaave: 2,
      jiaedin: 2,
    },
    Nana4321: {
      Wild_West: 2,
      atomic: 4,
      awesomaave: 2,
      honestpretzels: 5,
      jiaedin: 3,
    },
    Spacebro: {
      Wild_West: 5,
      atomic: 1,
      awesomaave: 2,
      honestpretzels: 4,
      jiaedin: 2,
    },
    Wild_West: {
      MrGenericUser: 2,
      Nana4321: 1,
      Spacebro: 6,
      kevin: 1,
      nosidE: 5,
    },
    atomic: {
      MrGenericUser: 3,
      Nana4321: 10,
      Spacebro: 8,
      kevin: 9,
      nosidE: 4,
    },
    awesomaave: {
      MrGenericUser: 3,
      Nana4321: 4,
      Spacebro: 1,
      kevin: 1,
    },
    honestpretzels: {
      MrGenericUser: 8,
      Nana4321: 2,
      Spacebro: 4,
      kevin: 3,
      nosidE: 5,
    },
    jiaedin: {
      MrGenericUser: 6,
      Nana4321: 6,
      Spacebro: 3,
      kevin: 4,
      nosidE: 2,
    },
    kevin: {
      Wild_West: 9,
      atomic: 9,
      awesomaave: 11,
      honestpretzels: 9,
      jiaedin: 10,
    },
    nosidE: {
      Wild_West: 3,
      atomic: 4,
      awesomaave: 6,
      honestpretzels: 8,
      jiaedin: 10,
    },
  },
  flashesThrown: {
    MrGenericUser: 1,
    Nana4321: 8,
    Wild_West: 7,
    atomic: 31,
    honestpretzels: 19,
    jiaedin: 16,
    kevin: 33,
    nosidE: 24,
  },
  smokesThrown: {
    MrGenericUser: 2,
    Nana4321: 10,
    Wild_West: 6,
    atomic: 20,
    awesomaave: 7,
    honestpretzels: 14,
    jiaedin: 14,
    kevin: 23,
    nosidE: 8,
  },
  molliesThrown: {
    MrGenericUser: 9,
    Nana4321: 13,
    Spacebro: 10,
    Wild_West: 9,
    atomic: 8,
    awesomaave: 11,
    honestpretzels: 15,
    jiaedin: 18,
    kevin: 14,
    nosidE: 20,
  },
  HEsThrown: {
    MrGenericUser: 2,
    Spacebro: 10,
    atomic: 1,
    honestpretzels: 2,
    kevin: 2,
    nosidE: 1,
  },
  "2k": {
    MrGenericUser: 1,
    Nana4321: 3,
    Spacebro: 2,
    Wild_West: 4,
    atomic: 8,
    awesomaave: 3,
    honestpretzels: 5,
    jiaedin: 4,
    kevin: 9,
    nosidE: 7,
  },
  "3k": {
    Nana4321: 1,
    atomic: 2,
    honestpretzels: 2,
    jiaedin: 2,
    kevin: 4,
    nosidE: 4,
  },
  "4k": {
    kevin: 2,
  },
  "5k": {
    atomic: 1,
  },
};
